version: 2

run:
  timeout: 3m
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - errcheck
    - ineffassign
    - gocritic
    - gocyclo
    - revive

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/snobb

  errcheck:
    check-type-assertions: true
    check-blank: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
    goimports:
      local-prefixes:
        - github.com/snobb

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
